import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/navbar/Navbar'
import AtomLoader from '@/utility/AtomLoader'
import { Toaster } from 'react-hot-toast'
import Footer from '@/components/footer/Footer'
import PlayMusic from '@/components/playMusic/PlayMusic'
import ThemeProvider from '@/utility/ThemeProvider'


export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by Max',
}

export default function ProjectLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <AtomLoader />

        <div>
          <PlayMusic />
          <Navbar />
        </div>

        <Toaster
          position="top-center"
          reverseOrder={false}
        />
        {children}
        <Footer />
      </ThemeProvider>
    </html>
  )
}
