import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/Navbar'
import AtomLoader from '@/utility/AtomLoader'
import { Toaster } from 'react-hot-toast'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by Max',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AtomLoader />
        <Navbar />
        <Toaster
          position="top-center"
          reverseOrder={false}
        />
        {children}
        <Footer />
      </body>
    </html>
  )
}
